---
  - name: Create elastalert directory
    file:
      path: /etc/logstash/ssl
      state: directory
      mode: 0755
    become: yes

  - file:
      path: /etc/logstash/conf.d
      state: absent
  - file:
      path: /etc/logstash/conf.d
      state: directory

  - name: Copy logstash config
    template: src=log.conf dest=/etc/logstash/conf.d
    become: yes

  - name: Copy kibana config
    template: src=kibana.yml dest=/etc/kibana
    become: yes

  - name: Replace elastalert config with password
    template: src=config.yaml dest=/opt/{{ ea_dir }}
    become: yes
